packages:
  - packages/*
  - packages/@n8n/*
  - packages/@n8n_io/*
  - cypress

catalog:
  '@types/express': ^4.17.21
  '@types/lodash': ^4.14.195
  '@types/uuid': ^8.3.2
  '@types/xml2js': ^0.4.14
  axios: 1.6.7
  fast-glob: 3.2.12
  lodash: 4.17.21
  luxon: 3.4.4
  nanoid: 3.3.6
  typedi: 0.10.0
  uuid: 8.3.2
  vue: 3.4.21
  xml2js: 0.6.2
